trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: SolutionBaseName
  value: SFA.DAS.EmployerDemand.Api
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu

pool:
  name: DAS - Continuous Integration
  workspace:
    clean: all

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

  - job: 'DACPACBuild'
    pool:
      name: 'DAS - Continuous Integration'
      demands: Agent.OS -equals Windows_NT
    workspace:
      clean: all
    steps:
      - task: VSBuild@1
        displayName: 'Build DACPAC'
        inputs:
          solution: 'src/SFA.DAS.EmployerDemand.Database/SFA.DAS.EmployerDemand.Database.sqlproj'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            src/**/*.dacpac
          targetFolder: '$(build.artifactstagingdirectory)/publish'
      - task: PublishBuildArtifacts@1
