CREATE TABLE [dbo].[CourseDemandNotificationAudit]
(
    [Id] UNIQUEIDENTIFIER PRIMARY KEY,
    [CourseDemandId] UNIQUEIDENTIFIER NOT NULL,
    [DateCreated] DATETIME NOT NULL DEFAULT GETDATE(),
    [NotificationType] SMALLINT NOT NULL DEFAULT 0
)
GO